spring:
  application:
    name: game-catalog-api-aws
  banner:
    location: classpath:banner-${spring.profiles.active}.txt

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: ${DB_USER}       # usuário master do RDS
    password: ${DB_PASSWORD}     # senha master do RDS
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: true
    show-sql: true  # como ainda é teste, pode deixar true

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    log-request-details: true

server:
  port: 8085   # pode manter a mesma da dev se quiser

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: ERROR
      hibernate: ERROR
    com:
      games: DEBUG
  file:
    path: ArquivoDeLog-AWS.log   # log vai gerar arquivo no diretório do projeto

app:
  environment: aws
